name: build-and-test
run-name: Build and run unit tests
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: turtlebrowser/get-conan@main
      - run: cmake --workflow --preset ci-linux-clang-ninja-unit-test

